#           **From Light to Structure:**
# **A Data-Driven Analysis of Impressionism and Cubism**

---



---

## **Description:**

This project explores the transition between Impressionism and Cubism
using data analysis and visualization.


It focuses on:
- Temporal evolution
- Artist distribution
- Comparative artistic output

### **Imports**

In [1]:
import pandas as pd
import plotly.express as px

### **Dataset**

In [3]:
data = [
    # Impressionists
    ["Claude Monet", "France", 1872],
    ["Claude Monet", "France", 1880],
    ["Edgar Degas", "France", 1875],
    ["Pierre-Auguste Renoir", "France", 1876],
    ["Camille Pissarro", "Denmark", 1874],
    ["Berthe Morisot", "France", 1878],

    # Cubists
    ["Pablo Picasso", "Spain", 1907],
    ["Pablo Picasso", "Spain", 1912],
    ["Georges Braque", "France", 1908],
    ["Juan Gris", "Spain", 1915],
    ["Fernand Léger", "France", 1913],
    ["Robert Delaunay", "France", 1912],
]

df = pd.DataFrame(data, columns=["artist", "country", "year"])

print(df)

                   artist  country  year
0            Claude Monet   France  1872
1            Claude Monet   France  1880
2             Edgar Degas   France  1875
3   Pierre-Auguste Renoir   France  1876
4        Camille Pissarro  Denmark  1874
5          Berthe Morisot   France  1878
6           Pablo Picasso    Spain  1907
7           Pablo Picasso    Spain  1912
8          Georges Braque   France  1908
9               Juan Gris    Spain  1915
10          Fernand Léger   France  1913
11        Robert Delaunay   France  1912

### **Movement classification**

In [6]:
impressionists = [
    "Claude Monet", "Edgar Degas", "Pierre-Auguste Renoir",
    "Camille Pissarro", "Berthe Morisot"
]

cubists = [
    "Pablo Picasso", "Georges Braque", "Juan Gris",
    "Fernand Léger", "Robert Delaunay"
]

def assign_movement(artist):
    if artist in impressionists:
        return "Impressionism"
    elif artist in cubists:
        return "Cubism"
    else:
        return "Other"

df["movement"] = df["artist"].apply(assign_movement)

print(df)

                   artist  country  year       movement
0            Claude Monet   France  1872  Impressionism
1            Claude Monet   France  1880  Impressionism
2             Edgar Degas   France  1875  Impressionism
3   Pierre-Auguste Renoir   France  1876  Impressionism
4        Camille Pissarro  Denmark  1874  Impressionism
5          Berthe Morisot   France  1878  Impressionism
6           Pablo Picasso    Spain  1907         Cubism
7           Pablo Picasso    Spain  1912         Cubism
8          Georges Braque   France  1908         Cubism
9               Juan Gris    Spain  1915         Cubism
10          Fernand Léger   France  1913         Cubism
11        Robert Delaunay   France  1912         Cubism

### **Data cleaning**

In [9]:
df.isnull().sum()

artist      0
country     0
year        0
movement    0
dtype: int64

In [10]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [8]:
df = df.dropna()

df["year"] = df["year"].astype(int)

print(df)

                   artist  country  year       movement
0            Claude Monet   France  1872  Impressionism
1            Claude Monet   France  1880  Impressionism
2             Edgar Degas   France  1875  Impressionism
3   Pierre-Auguste Renoir   France  1876  Impressionism
4        Camille Pissarro  Denmark  1874  Impressionism
5          Berthe Morisot   France  1878  Impressionism
6           Pablo Picasso    Spain  1907         Cubism
7           Pablo Picasso    Spain  1912         Cubism
8          Georges Braque   France  1908         Cubism
9               Juan Gris    Spain  1915         Cubism
10          Fernand Léger   France  1913         Cubism
11        Robert Delaunay   France  1912         Cubism

### **Timeline analysis**

In [11]:
timeline = df.groupby(["year", "movement"]).size().reset_index(name="count")

fig = px.line(
    timeline,
    x="year",
    y="count",
    color="movement",
    title="Temporal Evolution of Impressionism and Cubism"
)

fig.show()

### **Geographical Analysis**

In [12]:
geo = df.groupby(["country", "movement"]).size().reset_index(name="count")

fig = px.bar(
    geo,
    x="country",
    y="count",
    color="movement",
    title="Geographical Distribution of Artists"
)

fig.show()

### **Artistic output comparison**

In [13]:
artist_output = df.groupby(["artist", "movement"]).size().reset_index(name="count")

fig = px.bar(
    artist_output,
    x="artist",
    y="count",
    color="movement",
    title="Artistic Output per Artist"
)

fig.show()

### **Distribution**

In [14]:
fig = px.box(
    df,
    x="movement",
    y="year",
    title="Distribution of Artwork Years"
)

fig.show()

## **Key Insights**

-----


- Impressionism and Cubism overlap slightly in time,
  suggesting a gradual transition rather than a sharp break.

- France appears as a central hub for both movements.

- Cubist artists show a tendency toward later and more
  concentrated production periods.

### **Limitations**

----
- Small dataset
- Movement classification is manually assigned
- Data does not represent full artistic production